/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteFhgsdArgs } from "./DeleteFhgsdArgs";
import { FhgsdFindManyArgs } from "./FhgsdFindManyArgs";
import { FhgsdFindUniqueArgs } from "./FhgsdFindUniqueArgs";
import { Fhgsd } from "./Fhgsd";
import { FhgsdService } from "../fhgsd.service";

@graphql.Resolver(() => Fhgsd)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FhgsdResolverBase {
  constructor(
    protected readonly service: FhgsdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Fhgsd",
    action: "read",
    possession: "any",
  })
  async _fhgsdsMeta(
    @graphql.Args() args: FhgsdFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Fhgsd])
  @nestAccessControl.UseRoles({
    resource: "Fhgsd",
    action: "read",
    possession: "any",
  })
  async fhgsds(@graphql.Args() args: FhgsdFindManyArgs): Promise<Fhgsd[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Fhgsd, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Fhgsd",
    action: "read",
    possession: "own",
  })
  async fhgsd(
    @graphql.Args() args: FhgsdFindUniqueArgs
  ): Promise<Fhgsd | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fhgsd)
  @nestAccessControl.UseRoles({
    resource: "Fhgsd",
    action: "delete",
    possession: "any",
  })
  async deleteFhgsd(
    @graphql.Args() args: DeleteFhgsdArgs
  ): Promise<Fhgsd | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
