/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteFgdArgs } from "./DeleteFgdArgs";
import { FgdFindManyArgs } from "./FgdFindManyArgs";
import { FgdFindUniqueArgs } from "./FgdFindUniqueArgs";
import { Fgd } from "./Fgd";
import { FgdService } from "../fgd.service";

@graphql.Resolver(() => Fgd)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FgdResolverBase {
  constructor(
    protected readonly service: FgdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Fgd",
    action: "read",
    possession: "any",
  })
  async _fgdsMeta(
    @graphql.Args() args: FgdFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Fgd])
  @nestAccessControl.UseRoles({
    resource: "Fgd",
    action: "read",
    possession: "any",
  })
  async fgds(@graphql.Args() args: FgdFindManyArgs): Promise<Fgd[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Fgd, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Fgd",
    action: "read",
    possession: "own",
  })
  async fgd(@graphql.Args() args: FgdFindUniqueArgs): Promise<Fgd | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fgd)
  @nestAccessControl.UseRoles({
    resource: "Fgd",
    action: "delete",
    possession: "any",
  })
  async deleteFgd(@graphql.Args() args: DeleteFgdArgs): Promise<Fgd | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
